#include "keys.h"
#include <GLFW/glfw3.h>
#include <stdio.h>

int keycode_to_glfw(keycode key) {
	switch (key) {
		case KEY_SPACE: return GLFW_KEY_SPACE;
		case KEY_APOSTROPHE:
		case KEY_COMMA: GLFW_KEY_COMMA;
		case KEY_MINUS: GLFW_KEY_MINUS;
		case KEY_PERIOD: GLFW_KEY_PERIOD;
		case KEY_SLASH: GLFW_KEY_SLASH;
		case KEY_0: GLFW_KEY_0;
		case KEY_1: GLFW_KEY_1;
		case KEY_2: GLFW_KEY_2;
		case KEY_3: GLFW_KEY_3;
		case KEY_4: GLFW_KEY_4;
		case KEY_5: GLFW_KEY_5;
		case KEY_6: GLFW_KEY_6;
		case KEY_7: GLFW_KEY_7;
		case KEY_8: GLFW_KEY_8;
		case KEY_9: GLFW_KEY_9;
		case KEY_SEMICOLON: GLFW_KEY_SEMICOLON;
		case KEY_EQUAL: GLFW_KEY_EQUAL;
		case KEY_A: return GLFW_KEY_A;
		case KEY_B: return GLFW_KEY_B;
		case KEY_C: return GLFW_KEY_C;
		case KEY_D: return GLFW_KEY_D;
		case KEY_E: return GLFW_KEY_E;
		case KEY_F: return GLFW_KEY_F;
		case KEY_G: return GLFW_KEY_G;
		case KEY_H: return GLFW_KEY_H;
		case KEY_I: return GLFW_KEY_I;
		case KEY_J: return GLFW_KEY_J;
		case KEY_K: return GLFW_KEY_K;
		case KEY_L: GLFW_KEY_L;
		case KEY_M: GLFW_KEY_M;
		case KEY_N: GLFW_KEY_N;
		case KEY_O: GLFW_KEY_O;
		case KEY_P: GLFW_KEY_P;
		case KEY_Q: GLFW_KEY_Q;
		case KEY_R: GLFW_KEY_R;
		case KEY_S: GLFW_KEY_S;
		case KEY_T: GLFW_KEY_T;
		case KEY_U: GLFW_KEY_U;
		case KEY_V: GLFW_KEY_V;
		case KEY_W: GLFW_KEY_W;
		case KEY_X: GLFW_KEY_X;
		case KEY_Y: GLFW_KEY_Y;
		case KEY_Z: GLFW_KEY_Z;
		case KEY_LEFT_BRACKET: GLFW_KEY_LEFT_BRACKET;
		case KEY_BACKSLASH: GLFW_KEY_BACKSLASH;
		case KEY_RIGHT_BRACKET: GLFW_KEY_RIGHT_BRACKET;
		case KEY_GRAVE_ACCENT: GLFW_KEY_GRAVE_ACCENT;
		case KEY_WORLD_1: GLFW_KEY_WORLD_1;
		case KEY_WORLD_2: GLFW_KEY_WORLD_2;
		case KEY_ESCAPE: GLFW_KEY_ESCAPE;
		case KEY_ENTER: GLFW_KEY_ENTER;
		case KEY_TAB: GLFW_KEY_TAB;
		case KEY_BACKSPACE: GLFW_KEY_BACKSPACE;
		case KEY_INSERT: GLFW_KEY_INSERT;
		case KEY_DELETE: GLFW_KEY_DELETE;
		case KEY_RIGHT: GLFW_KEY_RIGHT;
		case KEY_LEFT: GLFW_KEY_LEFT;
		case KEY_DOWN: GLFW_KEY_DOWN;
		case KEY_UP: GLFW_KEY_UP;
		case KEY_PAGE_UP: GLFW_KEY_PAGE_UP;
		case KEY_PAGE_DOWN: GLFW_KEY_PAGE_DOWN;
		case KEY_HOME: GLFW_KEY_HOME;
		case KEY_END: GLFW_KEY_END;
		case KEY_CAPS_LOCK: GLFW_KEY_CAPS_LOCK;
		case KEY_SCROLL_LOCK: GLFW_KEY_SCROLL_LOCK;
		case KEY_NUM_LOCK: GLFW_KEY_NUM_LOCK;
		case KEY_PRINT_SCREEN: GLFW_KEY_PRINT_SCREEN;
		case KEY_PAUSE: GLFW_KEY_PAUSE;
		case KEY_F1: GLFW_KEY_F1;
		case KEY_F2: GLFW_KEY_F2;
		case KEY_F3: GLFW_KEY_F3;
		case KEY_F4: GLFW_KEY_F4;
		case KEY_F5: GLFW_KEY_F5;
		case KEY_F6: GLFW_KEY_F6;
		case KEY_F7: GLFW_KEY_F7;
		case KEY_F8: GLFW_KEY_F8;
		case KEY_F9: GLFW_KEY_F9;
		case KEY_F10: GLFW_KEY_F10;
		case KEY_F11: GLFW_KEY_F11;
		case KEY_F12: GLFW_KEY_F12;
		case KEY_F13: GLFW_KEY_F13;
		case KEY_F14: GLFW_KEY_F14;
		case KEY_F15: GLFW_KEY_F15;
		case KEY_F16: GLFW_KEY_F16;
		case KEY_F17: GLFW_KEY_F17;
		case KEY_F18: GLFW_KEY_F18;
		case KEY_F19: GLFW_KEY_F19;
		case KEY_F20: GLFW_KEY_F20;
		case KEY_F21: GLFW_KEY_F21;
		case KEY_F22: GLFW_KEY_F22;
		case KEY_F23: GLFW_KEY_F23;
		case KEY_F24: GLFW_KEY_F24;
		case KEY_F25: GLFW_KEY_F25;
		case KEY_KP_0: GLFW_KEY_KP_0;
		case KEY_KP_1: GLFW_KEY_KP_1;
		case KEY_KP_2: GLFW_KEY_KP_2;
		case KEY_KP_3: GLFW_KEY_KP_3;
		case KEY_KP_4: GLFW_KEY_KP_4;
		case KEY_KP_5: GLFW_KEY_KP_5;
		case KEY_KP_6: GLFW_KEY_KP_6;
		case KEY_KP_7: GLFW_KEY_KP_7;
		case KEY_KP_8: GLFW_KEY_KP_8;
		case KEY_KP_9: GLFW_KEY_KP_9;
		case KEY_KP_DECIMAL: GLFW_KEY_KP_DECIMAL;
		case KEY_KP_DIVIDE: GLFW_KEY_KP_DIVIDE;
		case KEY_KP_MULTIPLY: GLFW_KEY_KP_MULTIPLY;
		case KEY_KP_SUBTRACT: GLFW_KEY_KP_SUBTRACT;
		case KEY_KP_ADD: GLFW_KEY_KP_ADD;
		case KEY_KP_ENTER: GLFW_KEY_KP_ENTER;
		case KEY_KP_EQUAL: GLFW_KEY_KP_EQUAL;
		case KEY_LEFT_SHIFT: GLFW_KEY_LEFT_SHIFT;
		case KEY_LEFT_CONTROL: GLFW_KEY_LEFT_CONTROL;
		case KEY_LEFT_ALT: GLFW_KEY_LEFT_ALT;
		case KEY_LEFT_SUPER: GLFW_KEY_LEFT_SUPER;
		case KEY_RIGHT_SHIFT: GLFW_KEY_RIGHT_SHIFT;
		case KEY_RIGHT_CONTROL: GLFW_KEY_RIGHT_CONTROL;
		case KEY_RIGHT_ALT: GLFW_KEY_RIGHT_ALT;
		case KEY_RIGHT_SUPER: GLFW_KEY_RIGHT_SUPER;
		case KEY_MENU: GLFW_KEY_MENU;

		default:
			fprintf(stderr, "Unknown keycode %d\n", key);
	}
	return GLFW_KEY_UNKNOWN;
}

keycode glfw_to_keycode(int key) {
	switch (key) {
		case GLFW_KEY_SPACE: return KEY_SPACE;
		case GLFW_KEY_APOSTROPHE: return KEY_APOSTROPHE;
		case GLFW_KEY_COMMA: return KEY_COMMA;
		case GLFW_KEY_MINUS: return KEY_MINUS;
		case GLFW_KEY_PERIOD: return KEY_PERIOD;
		case GLFW_KEY_SLASH: return KEY_SLASH;
		case GLFW_KEY_0: return KEY_0;
		case GLFW_KEY_1: return KEY_1;
		case GLFW_KEY_2: return KEY_2;
		case GLFW_KEY_3: return KEY_3;
		case GLFW_KEY_4: return KEY_4;
		case GLFW_KEY_5: return KEY_5;
		case GLFW_KEY_6: return KEY_6;
		case GLFW_KEY_7: return KEY_7;
		case GLFW_KEY_8: return KEY_8;
		case GLFW_KEY_9: return KEY_9;
		case GLFW_KEY_SEMICOLON: return KEY_SEMICOLON;
		case GLFW_KEY_EQUAL: return KEY_EQUAL;
		case GLFW_KEY_A: return KEY_A;
		case GLFW_KEY_B: return KEY_B;
		case GLFW_KEY_C: return KEY_C;
		case GLFW_KEY_D: return KEY_D;
		case GLFW_KEY_E: return KEY_E;
		case GLFW_KEY_F: return KEY_F;
		case GLFW_KEY_G: return KEY_G;
		case GLFW_KEY_H: return KEY_H;
		case GLFW_KEY_I: return KEY_I;
		case GLFW_KEY_J: return KEY_J;
		case GLFW_KEY_K: return KEY_K;
		case GLFW_KEY_L: return KEY_L;
		case GLFW_KEY_M: return KEY_M;
		case GLFW_KEY_N: return KEY_N;
		case GLFW_KEY_O: return KEY_O;
		case GLFW_KEY_P: return KEY_P;
		case GLFW_KEY_Q: return KEY_Q;
		case GLFW_KEY_R: return KEY_R;
		case GLFW_KEY_S: return KEY_S;
		case GLFW_KEY_T: return KEY_T;
		case GLFW_KEY_U: return KEY_U;
		case GLFW_KEY_V: return KEY_V;
		case GLFW_KEY_W: return KEY_W;
		case GLFW_KEY_X: return KEY_X;
		case GLFW_KEY_Y: return KEY_Y;
		case GLFW_KEY_Z: return KEY_Z;
		case GLFW_KEY_LEFT_BRACKET: return KEY_LEFT_BRACKET;
		case GLFW_KEY_BACKSLASH: return KEY_BACKSLASH;
		case GLFW_KEY_RIGHT_BRACKET: return KEY_RIGHT_BRACKET;
		case GLFW_KEY_GRAVE_ACCENT: return KEY_GRAVE_ACCENT;
		case GLFW_KEY_WORLD_1: return KEY_WORLD_1;
		case GLFW_KEY_WORLD_2: return KEY_WORLD_2;
		case GLFW_KEY_ESCAPE: return KEY_ESCAPE;
		case GLFW_KEY_ENTER: return KEY_ENTER;
		case GLFW_KEY_TAB: return KEY_TAB;
		case GLFW_KEY_BACKSPACE: return KEY_BACKSPACE;
		case GLFW_KEY_INSERT: return KEY_INSERT;
		case GLFW_KEY_DELETE: return KEY_DELETE;
		case GLFW_KEY_RIGHT: return KEY_RIGHT;
		case GLFW_KEY_LEFT: return KEY_LEFT;
		case GLFW_KEY_DOWN: return KEY_DOWN;
		case GLFW_KEY_UP: return KEY_UP;
		case GLFW_KEY_PAGE_UP: return KEY_PAGE_UP;
		case GLFW_KEY_PAGE_DOWN: return KEY_PAGE_DOWN;
		case GLFW_KEY_HOME: return KEY_HOME;
		case GLFW_KEY_END: return KEY_END;
		case GLFW_KEY_CAPS_LOCK: return KEY_CAPS_LOCK;
		case GLFW_KEY_SCROLL_LOCK: return KEY_SCROLL_LOCK;
		case GLFW_KEY_NUM_LOCK: return KEY_NUM_LOCK;
		case GLFW_KEY_PRINT_SCREEN: return KEY_PRINT_SCREEN;
		case GLFW_KEY_PAUSE: return KEY_PAUSE;
		case GLFW_KEY_F1: return KEY_F1;
		case GLFW_KEY_F2: return KEY_F2;
		case GLFW_KEY_F3: return KEY_F3;
		case GLFW_KEY_F4: return KEY_F4;
		case GLFW_KEY_F5: return KEY_F5;
		case GLFW_KEY_F6: return KEY_F6;
		case GLFW_KEY_F7: return KEY_F7;
		case GLFW_KEY_F8: return KEY_F8;
		case GLFW_KEY_F9: return KEY_F9;
		case GLFW_KEY_F10: return KEY_F10;
		case GLFW_KEY_F11: return KEY_F11;
		case GLFW_KEY_F12: return KEY_F12;
		case GLFW_KEY_F13: return KEY_F13;
		case GLFW_KEY_F14: return KEY_F14;
		case GLFW_KEY_F15: return KEY_F15;
		case GLFW_KEY_F16: return KEY_F16;
		case GLFW_KEY_F17: return KEY_F17;
		case GLFW_KEY_F18: return KEY_F18;
		case GLFW_KEY_F19: return KEY_F19;
		case GLFW_KEY_F20: return KEY_F20;
		case GLFW_KEY_F21: return KEY_F21;
		case GLFW_KEY_F22: return KEY_F22;
		case GLFW_KEY_F23: return KEY_F23;
		case GLFW_KEY_F24: return KEY_F24;
		case GLFW_KEY_F25: return KEY_F25;
		case GLFW_KEY_KP_0: return KEY_KP_0;
		case GLFW_KEY_KP_1: return KEY_KP_1;
		case GLFW_KEY_KP_2: return KEY_KP_2;
		case GLFW_KEY_KP_3: return KEY_KP_3;
		case GLFW_KEY_KP_4: return KEY_KP_4;
		case GLFW_KEY_KP_5: return KEY_KP_5;
		case GLFW_KEY_KP_6: return KEY_KP_6;
		case GLFW_KEY_KP_7: return KEY_KP_7;
		case GLFW_KEY_KP_8: return KEY_KP_8;
		case GLFW_KEY_KP_9: return KEY_KP_9;
		case GLFW_KEY_KP_DECIMAL: return KEY_KP_DECIMAL;
		case GLFW_KEY_KP_DIVIDE: return KEY_KP_DIVIDE;
		case GLFW_KEY_KP_MULTIPLY: return KEY_KP_MULTIPLY;
		case GLFW_KEY_KP_SUBTRACT: return KEY_KP_SUBTRACT;
		case GLFW_KEY_KP_ADD: return KEY_KP_ADD;
		case GLFW_KEY_KP_ENTER: return KEY_KP_ENTER;
		case GLFW_KEY_KP_EQUAL: return KEY_KP_EQUAL;
		case GLFW_KEY_LEFT_SHIFT: return KEY_LEFT_SHIFT;
		case GLFW_KEY_LEFT_CONTROL: return KEY_LEFT_CONTROL;
		case GLFW_KEY_LEFT_ALT: return KEY_LEFT_ALT;
		case GLFW_KEY_LEFT_SUPER: return KEY_LEFT_SUPER;
		case GLFW_KEY_RIGHT_SHIFT: return KEY_RIGHT_SHIFT;
		case GLFW_KEY_RIGHT_CONTROL: return KEY_RIGHT_CONTROL;
		case GLFW_KEY_RIGHT_ALT: return KEY_RIGHT_ALT;
		case GLFW_KEY_RIGHT_SUPER: return KEY_RIGHT_SUPER;
		case GLFW_KEY_MENU: return KEY_MENU;
	}
	return KEY_UNDEFINED;
}

int mousebutton_to_glfw(mousebutton button) {
	switch (button) {
		case MOUSE_BUTTON_1: return GLFW_MOUSE_BUTTON_1;
		case MOUSE_BUTTON_2: return GLFW_MOUSE_BUTTON_2;
		case MOUSE_BUTTON_3: return GLFW_MOUSE_BUTTON_3;
		case MOUSE_BUTTON_4: return GLFW_MOUSE_BUTTON_4;
		case MOUSE_BUTTON_5: return GLFW_MOUSE_BUTTON_5;
		case MOUSE_BUTTON_6: return GLFW_MOUSE_BUTTON_6;
		case MOUSE_BUTTON_7: return GLFW_MOUSE_BUTTON_7;
		case MOUSE_BUTTON_8: return GLFW_MOUSE_BUTTON_8;
	}
	return GLFW_MOUSE_BUTTON_1;
}

mousebutton glfw_to_mousebutton(int button) {
	switch (button) {
		case GLFW_MOUSE_BUTTON_1: return MOUSE_BUTTON_1;
		case GLFW_MOUSE_BUTTON_2: return MOUSE_BUTTON_2;
		case GLFW_MOUSE_BUTTON_3: return MOUSE_BUTTON_3;
		case GLFW_MOUSE_BUTTON_4: return MOUSE_BUTTON_4;
		case GLFW_MOUSE_BUTTON_5: return MOUSE_BUTTON_5;
		case GLFW_MOUSE_BUTTON_6: return MOUSE_BUTTON_6;
		case GLFW_MOUSE_BUTTON_7: return MOUSE_BUTTON_7;
		case GLFW_MOUSE_BUTTON_8: return MOUSE_BUTTON_8;
	}
	return MOUSE_BUTTON_1;
}

int gamepadbutton_to_glfw(gamepad_button button) {
	switch (button) {
		case GAMEPAD_BUTTON_A: return GLFW_GAMEPAD_BUTTON_A;
		case GAMEPAD_BUTTON_B: return GLFW_GAMEPAD_BUTTON_B;
		case GAMEPAD_BUTTON_X: return GLFW_GAMEPAD_BUTTON_X;
		case GAMEPAD_BUTTON_Y: return GLFW_GAMEPAD_BUTTON_Y;
		case GAMEPAD_BUTTON_LEFT_BUMPER: return GLFW_GAMEPAD_BUTTON_LEFT_BUMPER;
		case GAMEPAD_BUTTON_RIGHT_BUMPER: return GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER;
		case GAMEPAD_BUTTON_BACK: return GLFW_GAMEPAD_BUTTON_BACK;
		case GAMEPAD_BUTTON_START: return GLFW_GAMEPAD_BUTTON_START;
		case GAMEPAD_BUTTON_GUIDE: return GLFW_GAMEPAD_BUTTON_GUIDE;
		case GAMEPAD_BUTTON_LEFT_THUMB: return GLFW_GAMEPAD_BUTTON_LEFT_THUMB;
		case GAMEPAD_BUTTON_RIGHT_THUMB : return GLFW_GAMEPAD_BUTTON_RIGHT_THUMB; 
		case GAMEPAD_BUTTON_DPAD_UP: return GLFW_GAMEPAD_BUTTON_DPAD_UP;
		case GAMEPAD_BUTTON_DPAD_RIGHT: return GLFW_GAMEPAD_BUTTON_DPAD_RIGHT;
		case GAMEPAD_BUTTON_DPAD_DOWN: return GLFW_GAMEPAD_BUTTON_DPAD_DOWN;
		case GAMEPAD_BUTTON_DPAD_LEFT: return GLFW_GAMEPAD_BUTTON_DPAD_LEFT;
	}
	return GLFW_GAMEPAD_BUTTON_A;
}

gamepad_button glfw_to_gamepadbutton(int button) {
	switch (button) {
		case GLFW_GAMEPAD_BUTTON_A: return GAMEPAD_BUTTON_A;
		case GLFW_GAMEPAD_BUTTON_B: return GAMEPAD_BUTTON_B;
		case GLFW_GAMEPAD_BUTTON_X: return GAMEPAD_BUTTON_X;
		case GLFW_GAMEPAD_BUTTON_Y: return GAMEPAD_BUTTON_Y;
		case GLFW_GAMEPAD_BUTTON_LEFT_BUMPER: return GAMEPAD_BUTTON_LEFT_BUMPER;
		case GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER: return GAMEPAD_BUTTON_RIGHT_BUMPER;
		case GLFW_GAMEPAD_BUTTON_BACK: return GAMEPAD_BUTTON_BACK;
		case GLFW_GAMEPAD_BUTTON_START: return GAMEPAD_BUTTON_START;
		case GLFW_GAMEPAD_BUTTON_GUIDE: return GAMEPAD_BUTTON_GUIDE;
		case GLFW_GAMEPAD_BUTTON_LEFT_THUMB: return GAMEPAD_BUTTON_LEFT_THUMB;
		case GLFW_GAMEPAD_BUTTON_RIGHT_THUMB : return GAMEPAD_BUTTON_RIGHT_THUMB; 
		case GLFW_GAMEPAD_BUTTON_DPAD_UP: return GAMEPAD_BUTTON_DPAD_UP;
		case GLFW_GAMEPAD_BUTTON_DPAD_RIGHT: return GAMEPAD_BUTTON_DPAD_RIGHT;
		case GLFW_GAMEPAD_BUTTON_DPAD_DOWN: return GAMEPAD_BUTTON_DPAD_DOWN;
		case GLFW_GAMEPAD_BUTTON_DPAD_LEFT: return GAMEPAD_BUTTON_DPAD_LEFT;
	}
	return GLFW_GAMEPAD_BUTTON_A;
}
